{
 "title": "fieldstats4grafana",
 "tags": [
  "Home",
  "IOTA"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Common Field Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Season Progress (Percentage)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_season_completed" }
   ]
  },
  {
   "title": "Season",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_season_number_of_seasons" }
   ]
  },
  {
   "title": "Total Work Done (Points)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "field_season_score", "legendFormat": "Total Work Done (Points)" }
   ]
  },
  {
   "title": "Total IOTAS Donated (MIOTA)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_season_balance / 1000000" }
   ]
  },
  {
   "title": "Nodes Online",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_nodes_online" }
   ]
  },
  {
   "title": "Rank 1 Node (Points)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_node_nr1_score", "legendFormat": "Rank 1 Node (Points)" }
   ]
  },
  { "title": "Single Node Field Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node Score (Points)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "field_node_score", "legendFormat": "Node Score" }
   ]
  },
  {
   "title": "Delta No 1 Node (Points)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "format": "none",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "field_node_nr1_score - field_node_score",
     "legendFormat": "Delta No 1 Node (Points)"
    }
   ]
  },
  {
   "title": "Node Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "format": "none",
   "valueName": "current",
   "yaxes": [
    { "format": "none", "label": "MIOTA" }
   ],
   "targets": [
    {
     "expr": "field_node_balance_iota / 1000000",
     "legendFormat": "Balance (MIOTA)"
    },
    { "expr": "field_node_balance_usd", "legendFormat": "Balance (Dollar)" }
   ]
  },
  {
   "title": "Node Rank",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_node_rank" }
   ]
  },
  {
   "title": "Node Score (Percentage)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(field_node_score / field_season_score) * 100"
    }
   ]
  },
  { "title": "Season History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Seasons Participated",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "field_node_season_participation"
    }
   ]
  },
  {
   "title": "Lowest Score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_node_season_workdonemin" }
   ]
  },
  {
   "title": "Highest Score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_node_season_workdonemax" }
   ]
  },
  {
   "title": "Average Score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "field_node_season_workdoneaverage"
    }
   ]
  },
  {
   "title": "Overall Score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_node_season_workdonesum" }
   ]
  },
  { "title": "Multiple Node Field Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Own Nodes Score (Points)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "field_multiple_nodes_score", "legendFormat": "Own Nodes Score (Points)" }
   ]
  },
  {
   "title": "Own Nodes Balance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "current",
   "yaxes": [
    { "format": "none", "label": "IOTA" }
   ],
   "targets": [
    {
     "expr": "field_multiple_nodes_balance_iota / 1000000",
     "legendFormat": "Balance (MIOTA)"
    },
    {
     "expr": "field_multiple_nodes_balance_usd",
     "legendFormat": "Balance (Dollar)"
    }
   ]
  },
  {
   "title": "Own Nodes Score (Percentage)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(field_multiple_nodes_score / field_season_score) * 100"
    }
   ]
  },
  {
   "title": "Lowest Rank Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_multiple_nodes_score_max" }
   ]
  },
  {
   "title": "Own Nodes (Count)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_multiple_nodes_number" }
   ]
  },
  {
   "title": "Highest Rank Node",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "field_multiple_nodes_score_min" }
   ]
  },
  {
   "title": "Average Rank",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "field_multiple_nodes_score_average"
    }
   ]
  }
 ]
}